---
- hosts: web
  become: yes
  tasks:
  - name: install JDK 11
    apt:
      name: openjdk-11-jdk
      state: present

  - name: install tomcat 9
    apt:
      name: tomcat9
      state: present

  - name: install maven
    apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
    with_items:
    - maven
  
  - name: boxfuse
    become: yes
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /home/boxfuse/

  - name: maven clean package
    command: mvn -f "/home/boxfuse/pom.xml" clean package

  - name: copy boxfuse-sample-java-war-hello.war
    shell: cp "/home/boxfuse/target/hello-1.0.war" "/var/lib/tomcat9/webapps/"